export const SET_LOADING = "SET_LOADING";

//get all data
export const GET_USER_FOLDERS_AND_FILES = "GET_USER_FOLDERS_AND_FILES";

//folders
export const CREATE_FOLDER = "CREATE_FOLDER";
export const RESET_FOLDERS_FILES = "RESET_FOLDERS_FILES";
export const CHANGE_CURRENT_PATH = "CHANGE_CURRENT_PATH";

//files
export const CREATE_USER_FILE = "CREATE_USER_FILE";
export const UPDATE_USER_FILE_DATA = "UPDATE_USER_FILE_DATA";